/**
 * LearningInsight - Renders the learning insight message
 * Displays the improvement summary generated by ProgressSummaryBuilder
 * Pure rendering component - no interpretation or additional text
 */
class LearningInsight {
    /**
     * Render learning insight section
     * @param {Object} summary - Progress summary object
     */
    static render(summary) {
        const container = document.getElementById('learning-insight');
        if (!container) return;

        const { learningInsight } = summary;
        const { isImproving, improvementSummary } = learningInsight;

        // Get visual styling based on improvement status
        const { icon, colorClass, bgClass } = this.getInsightStyling(isImproving);

        container.innerHTML = `
            <div class="glass-panel rounded-xl p-8 text-center">
                <div class="mb-6">
                    <div class="text-6xl mb-4">${icon}</div>
                    <h2 class="text-xl font-bold mb-2">Learning Insight</h2>
                </div>
                
                <div class="${bgClass} rounded-lg p-6 max-w-2xl mx-auto">
                    <p class="${colorClass} text-lg font-medium leading-relaxed">
                        ${improvementSummary}
                    </p>
                </div>

                ${this.renderInsightFooter(isImproving)}
            </div>
        `;
    }

    /**
     * Get styling information based on improvement status
     * @param {boolean|null} isImproving - Improvement status
     * @returns {Object} Styling information
     */
    static getInsightStyling(isImproving) {
        if (isImproving === true) {
            return {
                icon: '🎉',
                colorClass: 'text-green-300',
                bgClass: 'bg-green-900/30 border border-green-700/50'
            };
        } else if (isImproving === false) {
            return {
                icon: '💪',
                colorClass: 'text-orange-300',
                bgClass: 'bg-orange-900/30 border border-orange-700/50'
            };
        } else {
            return {
                icon: '📊',
                colorClass: 'text-blue-300',
                bgClass: 'bg-blue-900/30 border border-blue-700/50'
            };
        }
    }

    /**
     * Render footer with additional context based on improvement status
     * @param {boolean|null} isImproving - Improvement status
     * @returns {string} HTML string
     */
    static renderInsightFooter(isImproving) {
        let footerText = '';
        let footerClass = 'text-gray-400';

        if (isImproving === true) {
            footerText = 'Keep up the great work! Your skills are developing well.';
            footerClass = 'text-green-400';
        } else if (isImproving === false) {
            footerText = 'Every expert was once a beginner. Keep practicing!';
            footerClass = 'text-orange-400';
        } else {
            footerText = 'Continue playing to build more detailed progress insights.';
            footerClass = 'text-blue-400';
        }

        return `
            <div class="mt-6 pt-4 border-t border-gray-700">
                <p class="${footerClass} text-sm italic">
                    ${footerText}
                </p>
            </div>
        `;
    }
}

// Export for global access
window.LearningInsight = LearningInsight;